config/routes.rb
Rails.application.routes.draw do
  root "contacts#index"
  resources :contacts do
    collection { post :import }
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
require 'csv'
class Contact < ApplicationRecord
  belongs_to :user
  before_save :add_cc_franchise
  
  validates_uniqueness_of :email, :scope => :user_id
  validates_presence_of :name, :email, :birth_date, :phone, :address, :cc
  validates :cc, credit_card_number: { brands: [:amex, :jcb, :diners,:mastercard, :visa ] }
  validates_datetime :birth_date

  phony_normalize :phone, default_country_code: 'COL'
  validates_plausible_phone :phone

  def add_cc_franchise
    card = CreditCardValidations::Detector.new(self.cc)
    self.cc_franchise = card.brand
  end

  def self.import(file, user_id, column_names = {})
    column_names = column_names.reject { |k, v| v.empty? }

    CSV.foreach(file.path, headers: true) do |row|
      row = row.to_hash
      column_names.each do |key, value|
        row[key] = row.delete(value)
      end

      contact = Contact.new(row)
      contact.user_id = user_id

      contact.save!
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :contacts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[ edit create update destroy import ]
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :set_contacts, only: %i[ index ]

  def index
    @pagy, @records = pagy(@contacts, items: 10)
  end

  def show
  end

  def new
    @contact = Contact.new
  end

  def edit
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.user_id = @user.id

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def import
    begin
      Contact.import(params[:file], @user.id, colums_params.to_hash)
    rescue ActiveRecord::RecordInvalid
      redirect_to contacts_path, alert: "Contact import aborted! Found duplicated emails in your CSV file."
    rescue ActiveModel::UnknownAttributeError
      redirect_to contacts_path, alert: "Contact import aborted! Found unknown attributes in your CSV file. Please specify your header names above."
    else
      redirect_to contacts_path, notice:  "Contacts imported successfully"
    end
    
  end

  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_contacts
    @contacts = current_user.contacts
  end

  def set_contact
    @contact = Contact.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  def contact_params
    params.require(:contact).permit(:name, :birth_date, :phone, :address, :cc, :email)
  end

  def colums_params
    params.require(:columns).permit(:name, :birth_date, :phone, :address, :cc, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :birth_date %>
    <%= form.datetime_select :birth_date %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :cc, "Credit Card number" %>
    <%= form.text_field :cc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Birth date</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Cc</th>
      <th>Cc franchise</th>
      <th>Email</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.birth_date %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.address %></td>
        <td><%= contact.cc %></td>
        <td><%= contact.cc_franchise %></td>
        <td><%= contact.email %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%== pagy_nav(@pagy) %>
<br>
<style>
  .column_labels {
    text-transform: lowercase;
    margin-top: 10px;
    display: inline-block;
    width: 100px;
  }
</style>
<h3>Import Contacts</h3>
<%= form_tag import_contacts_path, multipart: true do %>
  <p>
    If your CSV file has different column headers to the ones below, please specify their name, otherwise leave the following fields empty.
  </p>
  <%= label :name, "name", class: "column_labels" %>
  <%= text_field :columns, :name %><br>
  <%= label :email, "email", class: "column_labels" %>
  <%= text_field :columns, :email %><br>
  <%= label :birth_date, "birth_date", class: "column_labels" %>
  <%= text_field :columns, :birth_date %><br>
  <%= label :phone, "phone", class: "column_labels" %>
  <%= text_field :columns, :phone %><br>
  <%= label :address, "address", class: "column_labels" %>
  <%= text_field :columns, :address %><br>
  <%= label :cc, "cc", class: "column_labels" %>
  <%= text_field :columns, :cc %><br><br>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload contacts CSV" %>
<% end %>
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<br>
<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @contact.birth_date %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @contact.address %>
</p>

<p>
  <strong>Cc:</strong>
  <%= @contact.cc %>
</p>

<p>
  <strong>Cc franchise:</strong>
  <%= @contact.cc_franchise %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactImporter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    <%= yield %>
  </body>
</html>